---
- name: Upgrade ArgoCD
  hosts: management
  become: true
  vars_files:
    - ../group_vars/all.yml
    - patch-versions.yml

  tasks:
    - name: Get current ArgoCD version
      kubernetes.core.helm_info:
        name: argocd
        release_namespace: argocd
        kubeconfig: "{{ rke2_kubeconfig }}"
      register: argocd_info
      failed_when: false

    - name: Skip if not installed
      ansible.builtin.debug:
        msg: "ArgoCD not installed, skipping upgrade"
      when: argocd_info.status is not defined

    - name: Upgrade ArgoCD
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo-cd
        chart_repo_url: https://argoproj.github.io/argo-helm
        release_namespace: argocd
        chart_version: "{{ argocd_version }}"
        kubeconfig: "{{ rke2_kubeconfig }}"
        update_repo_cache: true
        wait: true
        timeout: "10m"
        values:
          server:
            service:
              type: ClusterIP
          configs:
            params:
              server.insecure: true
      when: argocd_info.status is defined
      register: argocd_upgraded

    - name: Wait for ArgoCD pods to be ready
      ansible.builtin.shell: |
        {{ rke2_bin_path }}/kubectl --kubeconfig={{ rke2_kubeconfig }} \
        wait --for=condition=Ready pod -l app.kubernetes.io/name=argocd-server -n argocd --timeout=300s
      when: argocd_upgraded is changed
      changed_when: false
      failed_when: false

    - name: Display upgrade status
      ansible.builtin.debug:
        msg: "✅ ArgoCD upgraded to {{ argocd_version }}"
      when: argocd_upgraded is changed
