---
- name: Upgrade RKE2
  hosts: all
  become: true
  serial: 1
  vars_files:
    - ../group_vars/all.yml
    - patch-versions.yml

  tasks:
    - name: Check current RKE2 version
      ansible.builtin.shell: /usr/local/bin/rke2 --version | head -1 | awk '{print $3}'
      register: current_rke2
      changed_when: false
      failed_when: false

    - name: Skip if already on target version
      ansible.builtin.debug:
        msg: "RKE2 already at {{ rke2_version }}, skipping upgrade"
      when: current_rke2.stdout == rke2_version

    - name: Upgrade RKE2
      ansible.builtin.shell: |
        curl -sfL {{ rke2_install_url }} | \
        INSTALL_RKE2_TYPE='{{ "server" if ("management" in group_names or "key_control" in group_names) else "agent" }}' \
        INSTALL_RKE2_VERSION='{{ rke2_version }}' sh -
      args:
        executable: /bin/bash
      when: current_rke2.stdout != rke2_version
      register: rke2_upgrade

    - name: Restart RKE2 service
      ansible.builtin.systemd:
        name: "{{ 'rke2-server' if ('management' in group_names or 'key_control' in group_names) else 'rke2-agent' }}"
        state: restarted
        enabled: true
        daemon_reload: true
      when: rke2_upgrade is changed
      async: 600
      poll: 0
      register: rke2_restart

    - name: Wait for RKE2 service to stabilize
      ansible.builtin.async_status:
        jid: "{{ rke2_restart.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 60
      delay: 10
      when: rke2_upgrade is changed

    - name: Wait for node to be ready
      ansible.builtin.command: >
        {{ rke2_bin_path }}/kubectl --kubeconfig={{ rke2_kubeconfig }}
        wait --for=condition=Ready node/{{ inventory_hostname }} --timeout=300s
      when: "'management' in group_names or 'key_control' in group_names"
      changed_when: false

    - name: Re-apply CoreDNS config with Rancher hostname (downstream only)
      kubernetes.core.k8s:
        state: present
        kind: ConfigMap
        name: rke2-coredns-rke2-coredns
        namespace: kube-system
        definition:
          data:
            Corefile: |
              .:53 {
                  errors
                  health {
                      lameduck 10s
                  }
                  ready
                  hosts {
                      {{ base_ip }}.{{ management_ip_num }} {{ rancher_hostname }}
                      fallthrough
                  }
                  kubernetes cluster.local cluster.local in-addr.arpa ip6.arpa {
                      pods insecure
                      fallthrough in-addr.arpa ip6.arpa
                      ttl 30
                  }
                  prometheus 0.0.0.0:9153
                  forward . 8.8.8.8 1.1.1.1
                  cache 30
                  loop
                  reload
                  loadbalance
              }
        kubeconfig: "{{ rke2_kubeconfig }}"
      when:
        - rke2_upgrade is changed
        - "'key_control' in group_names"
      failed_when: false

    - name: Restart CoreDNS pods after upgrade (downstream only)
      kubernetes.core.k8s:
        state: absent
        kind: Pod
        namespace: kube-system
        label_selectors:
          - k8s-app=kube-dns
        kubeconfig: "{{ rke2_kubeconfig }}"
      when:
        - rke2_upgrade is changed
        - "'key_control' in group_names"
      failed_when: false

    - name: Wait for CoreDNS to be ready after upgrade
      kubernetes.core.k8s_info:
        kind: Deployment
        name: rke2-coredns-rke2-coredns
        namespace: kube-system
        kubeconfig: "{{ rke2_kubeconfig }}"
        wait: true
        wait_condition:
          type: Available
          status: "True"
        wait_timeout: 120
      when:
        - rke2_upgrade is changed
        - "'key_control' in group_names"
      failed_when: false

    - name: Display upgrade status
      ansible.builtin.debug:
        msg: "✅ {{ inventory_hostname }} upgraded to {{ rke2_version }}"

    - name: Wait before next node
      ansible.builtin.pause:
        seconds: 30
