---
- name: Upgrade Kargo
  hosts: management
  become: true
  vars_files:
    - ../group_vars/all.yml
    - patch-versions.yml

  tasks:
    - name: Get current Kargo version
      ansible.builtin.shell: |
        {{ rke2_bin_path }}/kubectl --kubeconfig={{ rke2_kubeconfig }} \
        get helmchart kargo -n kube-system -o jsonpath='{.spec.version}' 2>/dev/null || echo "not-installed"
      register: current_kargo
      changed_when: false

    - name: Skip if not installed
      ansible.builtin.debug:
        msg: "Kargo not installed, skipping upgrade"
      when: current_kargo.stdout == "not-installed"

    - name: Skip if already on target version
      ansible.builtin.debug:
        msg: "Kargo already at {{ kargo_version }}, skipping upgrade"
      when: current_kargo.stdout == kargo_version

    - name: Upgrade Kargo HelmChart
      ansible.builtin.shell: |
        {{ rke2_bin_path }}/kubectl --kubeconfig={{ rke2_kubeconfig }} \
        patch helmchart kargo -n kube-system --type='merge' \
        -p '{"spec":{"version":"{{ kargo_version }}"}}'
      when: current_kargo.stdout != kargo_version and current_kargo.stdout != "not-installed"
      register: kargo_upgraded

    - name: Wait for Kargo pods to be ready
      ansible.builtin.shell: |
        {{ rke2_bin_path }}/kubectl --kubeconfig={{ rke2_kubeconfig }} \
        wait --for=condition=Ready pod -l app.kubernetes.io/name=kargo -n kargo --timeout=300s
      when: kargo_upgraded is changed
      changed_when: false
      failed_when: false

    - name: Display upgrade status
      ansible.builtin.debug:
        msg: "✅ Kargo upgraded: {{ current_kargo.stdout }} → {{ kargo_version }}"
      when: kargo_upgraded is changed
