---
- name: Upgrade RKE2
  hosts: all
  become: true
  serial: 1
  vars_files:
    - ../group_vars/all.yml
    - patch-versions.yml
  vars:
    # Determine if this is a server (control plane) or agent (worker) node
    is_server: "{{ 'management' in group_names or 'key_control' in group_names }}"
    is_worker: "{{ 'key_workers' in group_names }}"
    rke2_service_name: "{{ 'rke2-server' if is_server else 'rke2-agent' }}"
    # Use management node for kubectl commands (it has the kubeconfig)
    kubectl_delegate: "{{ groups['management'][0] }}"

  tasks:
    - name: Check current RKE2 version
      ansible.builtin.shell: /usr/local/bin/rke2 --version | head -1 | awk '{print $3}'
      register: current_rke2
      changed_when: false
      failed_when: false

    - name: Skip if already on target version
      ansible.builtin.debug:
        msg: "RKE2 already at {{ rke2_version }}, skipping upgrade"
      when: current_rke2.stdout == rke2_version

    - name: Set upgrade required fact
      ansible.builtin.set_fact:
        upgrade_required: "{{ current_rke2.stdout != rke2_version }}"

    # === CORDON NODE ===
    - name: Cordon node to prevent new pod scheduling
      ansible.builtin.command: >
        {{ rke2_bin_path }}/kubectl --kubeconfig={{ rke2_kubeconfig }}
        cordon {{ inventory_hostname }}
      delegate_to: "{{ kubectl_delegate }}"
      become: true
      when: upgrade_required
      register: cordon_result
      changed_when: "'cordoned' in cordon_result.stdout"

    # === DRAIN NODE (only for workers with multiple nodes) ===
    - name: Drain workloads from worker node
      ansible.builtin.command: >
        {{ rke2_bin_path }}/kubectl --kubeconfig={{ rke2_kubeconfig }}
        drain {{ inventory_hostname }}
        --ignore-daemonsets
        --delete-emptydir-data
        --force
        --grace-period=60
        --timeout=300s
      delegate_to: "{{ kubectl_delegate }}"
      become: true
      when:
        - upgrade_required
        - is_worker
      register: drain_result
      changed_when: "'evicting' in drain_result.stdout or 'evicted' in drain_result.stdout"
      failed_when:
        - drain_result.rc != 0
        - "'cannot delete Pods' not in drain_result.stderr"

    # === UPGRADE RKE2 ===
    - name: Upgrade RKE2
      ansible.builtin.shell: |
        curl -sfL {{ rke2_install_url }} | \
        INSTALL_RKE2_TYPE='{{ "server" if is_server else "agent" }}' \
        INSTALL_RKE2_VERSION='{{ rke2_version }}' sh -
      args:
        executable: /bin/bash
      when: upgrade_required
      register: rke2_upgrade

    # === RESTART RKE2 SERVICE ===
    - name: Restart RKE2 service
      ansible.builtin.systemd:
        name: "{{ rke2_service_name }}"
        state: restarted
        enabled: true
        daemon_reload: true
      when: rke2_upgrade is changed
      async: 600
      poll: 0
      register: rke2_restart

    - name: Wait for RKE2 service to stabilize
      ansible.builtin.async_status:
        jid: "{{ rke2_restart.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 60
      delay: 10
      when: rke2_upgrade is changed

    # === WAIT FOR NODE READY ===
    - name: Wait for node to be ready
      ansible.builtin.command: >
        {{ rke2_bin_path }}/kubectl --kubeconfig={{ rke2_kubeconfig }}
        wait --for=condition=Ready node/{{ inventory_hostname }} --timeout=300s
      delegate_to: "{{ kubectl_delegate }}"
      become: true
      when: upgrade_required
      changed_when: false
      retries: 3
      delay: 10
      register: node_ready
      until: node_ready.rc == 0

    # === UNCORDON NODE ===
    - name: Uncordon node to allow pod scheduling
      ansible.builtin.command: >
        {{ rke2_bin_path }}/kubectl --kubeconfig={{ rke2_kubeconfig }}
        uncordon {{ inventory_hostname }}
      delegate_to: "{{ kubectl_delegate }}"
      become: true
      when: upgrade_required
      register: uncordon_result
      changed_when: "'uncordoned' in uncordon_result.stdout"

    # === VERIFY NODE STATUS ===
    - name: Verify node is schedulable
      ansible.builtin.command: >
        {{ rke2_bin_path }}/kubectl --kubeconfig={{ rke2_kubeconfig }}
        get node {{ inventory_hostname }} -o jsonpath='{.spec.unschedulable}'
      delegate_to: "{{ kubectl_delegate }}"
      become: true
      register: node_schedulable
      failed_when: node_schedulable.stdout == 'true'
      changed_when: false
      when: upgrade_required

    - name: Display upgrade status
      ansible.builtin.debug:
        msg: "✅ {{ inventory_hostname }} upgraded to {{ rke2_version }} and uncordoned"
      when: upgrade_required

    - name: Display skip status
      ansible.builtin.debug:
        msg: "⏭️  {{ inventory_hostname }} already at {{ rke2_version }}, no action taken"
      when: not upgrade_required

    - name: Wait before next node
      ansible.builtin.pause:
        seconds: 30
      when: upgrade_required
