---
- name: Upgrade Sealed Secrets Controller
  hosts: management
  become: true
  vars_files:
    - ../group_vars/all.yml
    - patch-versions.yml

  tasks:
    - name: Get current Sealed Secrets version
      kubernetes.core.helm_info:
        name: sealed-secrets
        release_namespace: kube-system
        kubeconfig: "{{ rke2_kubeconfig }}"
      register: sealed_secrets_info
      failed_when: false

    - name: Skip if not installed
      ansible.builtin.debug:
        msg: "Sealed Secrets not installed, skipping upgrade"
      when: sealed_secrets_info.status is not defined

    - name: Display current version
      ansible.builtin.debug:
        msg: "Current Sealed Secrets chart version: {{ sealed_secrets_info.status.chart | default('unknown') }}"
      when: sealed_secrets_info.status is defined

    - name: Update Helm repository
      kubernetes.core.helm_repository:
        name: sealed-secrets
        repo_url: "{{ sealed_secrets_repo }}"
      environment:
        KUBECONFIG: "{{ rke2_kubeconfig }}"

    - name: Upgrade Sealed Secrets Controller
      kubernetes.core.helm:
        name: sealed-secrets
        chart_ref: sealed-secrets/sealed-secrets
        chart_version: "{{ sealed_secrets_version }}"
        release_namespace: kube-system
        kubeconfig: "{{ rke2_kubeconfig }}"
        update_repo_cache: true
        wait: true
        timeout: "5m"
        values:
          fullnameOverride: sealed-secrets-controller
      when: sealed_secrets_info.status is defined
      register: sealed_secrets_upgraded

    - name: Wait for Sealed Secrets controller to be ready
      ansible.builtin.shell: |
        {{ rke2_bin_path }}/kubectl --kubeconfig={{ rke2_kubeconfig }} \
        wait --for=condition=Ready pod -l app.kubernetes.io/name=sealed-secrets -n kube-system --timeout=120s
      when: sealed_secrets_upgraded is changed
      changed_when: false
      failed_when: false

    - name: Verify Sealed Secrets controller is running
      ansible.builtin.shell: |
        {{ rke2_bin_path }}/kubectl --kubeconfig={{ rke2_kubeconfig }} \
        get pods -n kube-system -l app.kubernetes.io/name=sealed-secrets -o jsonpath='{.items[0].status.phase}'
      register: controller_status
      when: sealed_secrets_upgraded is changed
      changed_when: false

    - name: Display upgrade status
      ansible.builtin.debug:
        msg: "Sealed Secrets upgraded to {{ sealed_secrets_version }} - Pod status: {{ controller_status.stdout | default('N/A') }}"
      when: sealed_secrets_upgraded is changed
